git:
  depth: 3
  submodules: false
branches:
  only:
  - master

dist:     trusty    
sudo:     required  

language: cpp
os:
    - linux
    - osx
  
compiler:
    - gcc
    - clang
matrix:
    exclude:
        - os:       osx
          compiler: gcc
        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release
before_install:
  - sudo apt -y install clang libc++-dev libclang-dev
install:
    # скрипт настройки среды и установки зависимостей:
    - source travis/install-$TRAVIS_OS_NAME.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
#    - ctest --output-on-failure
